version: "3"
services:
  postgres:
    container_name: postgres-local
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_BASE}
    volumes:
      - postgres_data_container:/data/db

volumes:
  postgres_data_container: