### Variables

@URI=http://0.0.0.0:7000
@TIME={{$timestamp}}

###

# @name AuthUser
POST {{URI}}/auth
Authorization: Basic {{CreateUser.response.body.email}} 12345

###

# @name CreateUser
POST {{URI}}/users
content-type: application/json

{
  "name" : "Douglas {{TIME}}",
  "email": "douglas.{{TIME}}@email.com",
  "password" : "12345",
  "admin": true
}

###

# @name GetUser
@USER_ID={{CreateUser.response.body.id}}
GET {{URI}}/users/{{USER_ID}}
Authorization: Bearer {{AuthUser.response.body.access_token}}

###

# @name CreateTag
POST {{URI}}/tags
content-type: application/json
Authorization: Bearer {{AuthUser.response.body.access_token}}
{
  "name" : "test_{{TIME}}"
}

###

# @name GetTag
@TAG_ID={{CreateTag.response.body.id}}
GET {{URI}}/tags/{{TAG_ID}}
Authorization: Bearer {{AuthUser.response.body.access_token}}

###

# @name CreateCompliment
POST {{URI}}/compliments
content-type: application/json
Authorization: Bearer {{AuthUser.response.body.access_token}}

{
  "senderId": "ba74f8a5-5251-4a3d-b7de-91633814ea31",
  "receiverId": "b32e582b-e5bb-4ebc-9399-e754d8584b42",
  "tagId": "{{TAG_ID}}",
  "message": "Obrigado!"
}

###

# @name GetCompliment
@COMPLIMENT_ID={{CreateCompliment.response.body.id}}
GET {{URI}}/compliments/{{COMPLIMENT_ID}}
Authorization: Bearer {{AuthUser.response.body.access_token}}

###

